#!/usr/bin/env python

import csv
import datetime
import hashlib
import sys

ics_file = 'david.birthdays.ics'
csv_file = '/tmp/contacts.csv'
if len(sys.argv) == 3:
	csv_file = sys.argv[1]
	ics_file = sys.argv[2]
elif len(sys.argv) == 2:
	if sys.argv[1].lower() == '-h':
		print('Usage: {} [csv_file [ics_file]]'.format(sys.argv[0]))
		print('Create a birthday calendar ICS output file from an exported CSV containing Google Contact information')
		print('Default file names: csv_file = "contacts.csv" and ics_file = "david.birthdays.ics"')
	else:
		csv_file = sys.argv[1]
		
with open(ics_file, 'w') as icsfile:
	print('BEGIN:VCALENDAR', file=icsfile)
	print('PRODID:-//Google Inc//Google Calendar 70.9054//EN', file=icsfile)
	print('VERSION:2.0', file=icsfile)
	print('CALSCALE:GREGORIAN', file=icsfile)
	print('METHOD:PUBLISH', file=icsfile)
	print('X-WR-TIMEZONE:America/New_York', file=icsfile)
	
	with open(csv_file) as csvfile:
		reader = csv.DictReader(csvfile)
		for row in reader:
			if row['Birthday'] != '':
				for ctr in range(0,3):
					this_year = int(datetime.datetime.utcnow().strftime('%Y')) + ctr

					y, m, d = row['Birthday'].split('-')
					now = datetime.datetime.utcnow().strftime('%Y%m%dT%H%M%SZ')

					print('BEGIN:VEVENT', file=icsfile)
					print('DTSTART;VALUE=DATE:{}{}{}'.format(this_year, m, d), file=icsfile)
					print('DTEND;VALUE=DATE:{}{}{:02d}'.format(this_year, m, int(d) + 1), file=icsfile)
					print('DTSTAMP:{}'.format(now), file=icsfile)

					something = row['Name'] + row['Birthday']
					print('UID:{}_BIRTHDAY_{}@google.com'.format(this_year, hashlib.sha1(something.encode('utf-8')).hexdigest()[:16]), file=icsfile)

					print('X-GOOGLE-CALENDAR-CONTENT-DISPLAY:chip', file=icsfile)
					print('X-GOOGLE-CALENDAR-CONTENT-ICON:https://calendar.google.com/googlecalendar/images/cake.gif', file=icsfile)
					print('CLASS:PUBLIC', file=icsfile)
					print('CREATED:{}'.format(now), file=icsfile)
					print('DESCRIPTION:This is {}\'s birthday!'.format(row['Name']), file=icsfile)
					print('LAST-MODIFIED:'.format(now), file=icsfile)
					print('SEQUENCE:0', file=icsfile)
					print('STATUS:CONFIRMED', file=icsfile)
					print('SUMMARY:{}\'s birthday'.format(row['Name']), file=icsfile)
					print('TRANSP:OPAQUE', file=icsfile)
					print('END:VEVENT', file=icsfile)

	print('END:VCALENDAR', file=icsfile)
